function createfigure(Vertices1, Faces1, FaceVertexCData1, Vertices2, FaceVertexCData2)
%CREATEFIGURE(VERTICES1, FACES1, FACEVERTEXCDATA1, VERTICES2, FACEVERTEXCDATA2)
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  FACEVERTEXCDATA1:  patch facevertexcdata
%  VERTICES2:  patch vertices
%  FACEVERTEXCDATA2:  patch facevertexcdata

%  Auto-generated by MATLAB on 25-Jan-2021 10:36:21

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);

% Create patch
patch('Parent',subplot1,'Vertices',Vertices1,'Faces',Faces1,...
    'FaceColor','interp',...
    'FaceVertexCData',FaceVertexCData1);

view(subplot1,[-0.380000000000003 -90]);
grid(subplot1,'on');
% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);

% Create patch
patch('Parent',subplot2,'Vertices',Vertices2,'Faces',Faces1,...
    'FaceColor','interp',...
    'FaceVertexCData',FaceVertexCData2);

view(subplot2,[-0.700000000000023 -90]);
grid(subplot2,'on');
